CREATE DATABASE DB_GEO
USE DB_GEO

CREATE TABLE TB_ENDERECOS(
COD_END INT IDENTITY(1,1) PRIMARY KEY,
ENDERECO VARCHAR (200),
LONG VARCHAR(30),
LAT VARCHAR(30)
)

CREATE PROCEDURE USP_CAD_END
@ENDERECO VARCHAR (200),
@LONG VARCHAR(30),
@LAT VARCHAR(30)

AS BEGIN 
	INSERT INTO TB_ENDERECOS VALUES (@ENDERECO , @LONG, @LAT)
END

CREATE PROCEDURE USP_CONSU_TODOS_END

AS BEGIN 
	SELECT ENDERECO AS 'Endereço', LONG AS 'Longetude' , LAT AS 'Latitude' FROM TB_ENDERECOS 
END

CREATE PROCEDURE USP_CONSU_END
@ENDERECO VARCHAR(200)
AS BEGIN 
	SELECT ENDERECO AS 'Endereço', LONG AS 'Longetude' , LAT AS 'Latitude' FROM TB_ENDERECOS WHERE ENDERECO LIKE '%'+@ENDERECO+'%' 
END

EXEC USP_CAD_END 'TESTE','122','123'

EXEC USP_CONSU_TODOS_END

EXEC USP_CONSU_END 'j'